# Generated by Django 3.0.8 on 2023-01-11 19:21

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.TextField()),
                ('query', models.TextField()),
                ('date_of_query', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_number', models.TextField()),
                ('image', models.ImageField(default='us_ma.png', upload_to='post_images/')),
                ('cv', models.FileField(blank=True, null=True, upload_to='post_files/')),
                ('cgpa', models.FloatField(default=0.0, null=True)),
                ('complete_address', models.TextField()),
                ('gender', models.TextField()),
                ('profile_filled', models.BooleanField(default=False)),
                ('profile_created', models.DateTimeField(default=datetime.datetime(2023, 1, 12, 0, 51, 44, 230129))),
                ('account_banned_permanent', models.BooleanField(default=False)),
                ('account_banned_temporary', models.BooleanField(default=False)),
                ('account_ban_date', models.DateTimeField(blank=True, null=True)),
                ('account_ban_time', models.IntegerField(default=0)),
                ('signup_date', models.DateTimeField(default=datetime.datetime(2023, 1, 12, 0, 51, 44, 230154))),
                ('verified', models.BooleanField(default=False)),
                ('otp_time', models.DateTimeField(default=datetime.datetime(2023, 1, 12, 0, 51, 44, 230162))),
                ('otp', models.TextField()),
                ('got_internship', models.BooleanField(default=False)),
                ('unique_code', models.TextField()),
                ('unique_code_time', models.DateTimeField(default=datetime.datetime(2023, 1, 12, 0, 51, 44, 230174))),
                ('code_expired', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_number', models.TextField()),
                ('complete_address', models.TextField()),
                ('image', models.ImageField(default='us_ma.png', upload_to='post_images/')),
                ('profile_filled', models.BooleanField(default=False)),
                ('profile_created', models.DateTimeField(default=datetime.datetime(2023, 1, 12, 0, 51, 44, 230451))),
                ('account_banned_permanent', models.BooleanField(default=False)),
                ('account_banned_temporary', models.BooleanField(default=False)),
                ('account_ban_date', models.DateTimeField(blank=True, null=True)),
                ('account_ban_time', models.IntegerField(default=0)),
                ('signup_date', models.DateTimeField(default=datetime.datetime(2023, 1, 12, 0, 51, 44, 230469))),
                ('verified', models.BooleanField(default=False)),
                ('otp_time', models.DateTimeField(default=datetime.datetime(2023, 1, 12, 0, 51, 44, 230476))),
                ('otp', models.TextField()),
                ('unique_code', models.TextField()),
                ('unique_code_time', models.DateTimeField(default=datetime.datetime(2023, 1, 12, 0, 51, 44, 230484))),
                ('code_expired', models.BooleanField(default=False)),
                ('let_staff_manage', models.BooleanField(default=False)),
                ('engaged', models.BooleanField(default=False)),
                ('is_this_staff_superuser', models.BooleanField(default=False)),
                ('staff_last_name', models.TextField()),
                ('staff_first_name', models.TextField()),
                ('original_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ORIGINAL', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='MAIN_USER', to=settings.AUTH_USER_MODEL)),
                ('user2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ORDINARY_USER', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
