# Generated by Django 3.0.8 on 2023-01-11 18:28

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('short_description', models.TextField()),
                ('brief_description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='post_images/')),
                ('date_of_announcement', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChatRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('message_time', models.DateTimeField(default=datetime.datetime(2023, 1, 11, 23, 58, 30, 499850))),
                ('chat_ended', models.BooleanField(default=False)),
                ('engaged', models.BooleanField(default=False)),
                ('engaged_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyAnnouncement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('general_announcement', models.BooleanField(default=False)),
                ('internship_round', models.TextField()),
                ('round_name', models.TextField()),
                ('first_round', models.BooleanField(default=False)),
                ('last_round', models.BooleanField(default=False)),
                ('last_round_result_announced', models.BooleanField(default=False)),
                ('prev_round_for_result', models.TextField()),
                ('last_date_to_apply', models.DateTimeField(default=datetime.datetime(2023, 1, 11, 23, 58, 30, 498861))),
                ('announcement_date', models.DateTimeField(default=datetime.datetime(2023, 1, 11, 23, 58, 30, 498867))),
                ('message', models.TextField()),
                ('file', models.FileField(blank=True, null=True, upload_to='post_files/')),
                ('file_for_prev_result', models.FileField(blank=True, null=True, upload_to='post_files/')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Internship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internship_name', models.TextField()),
                ('stipend', models.FloatField(default=0, null=True)),
                ('internship_duration', models.IntegerField(default=0, null=True)),
                ('internship_position', models.TextField()),
                ('minimum_cgpa', models.FloatField(default=5.0, null=True)),
                ('prerequisite', models.TextField()),
                ('result_announced', models.BooleanField(default=False)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('active', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(default=datetime.datetime(2023, 1, 11, 23, 58, 30, 498362))),
            ],
        ),
        migrations.CreateModel(
            name='TechnicalSupportRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('continued_support', models.BooleanField(default=False)),
                ('main_support_id', models.IntegerField(default=0)),
                ('message', models.TextField()),
                ('date', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_registrations', models.DateTimeField(default=datetime.datetime(2023, 1, 11, 23, 58, 30, 499168))),
                ('result_status', models.IntegerField(default=0)),
                ('internship_cleared', models.BooleanField(default=False)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.CompanyAnnouncement')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StaffPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_access_student_inactive_accounts', models.BooleanField(default=False)),
                ('can_access_company_inactive_accounts', models.BooleanField(default=False)),
                ('can_ban_users', models.BooleanField(default=False)),
                ('can_manage_blogs', models.BooleanField(default=False)),
                ('can_manage_technical_support', models.BooleanField(default=False)),
                ('can_give_notifications', models.BooleanField(default=False)),
                ('can_unban_users', models.BooleanField(default=False)),
                ('can_manage_staff_accounts', models.BooleanField(default=False)),
                ('can_delete_staff_accounts', models.BooleanField(default=False)),
                ('can_manage_sessions', models.BooleanField(default=False)),
                ('create_new_accounts', models.BooleanField(default=False)),
                ('manage_CGPA', models.BooleanField(default=False)),
                ('remove_students', models.BooleanField(default=False)),
                ('remove_companies', models.BooleanField(default=False)),
                ('can_manage_internships', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProfileVisibility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_registered_companies', models.BooleanField(default=False)),
                ('to_all_companies', models.BooleanField(default=False)),
                ('to_all_students', models.BooleanField(default=False)),
                ('to_all', models.BooleanField(default=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProfilePermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_who_can_see', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='can_see', to=settings.AUTH_USER_MODEL)),
                ('user_whose_to_see', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='whose_to_see', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification', models.TextField()),
                ('date', models.DateTimeField(default=datetime.datetime(2023, 1, 11, 23, 58, 30, 499724))),
                ('notification_receiver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_receiver', to=settings.AUTH_USER_MODEL)),
                ('notification_sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_sender', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InternshipFinalResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company', to=settings.AUTH_USER_MODEL)),
                ('internship', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.Internship')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='internship',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.Session'),
        ),
        migrations.AddField(
            model_name='companyannouncement',
            name='internship',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.Internship'),
        ),
        migrations.CreateModel(
            name='ChatResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField()),
                ('message', models.TextField()),
                ('message_time', models.DateTimeField(default=datetime.datetime(2023, 1, 11, 23, 58, 30, 500008))),
                ('mess_time_str', models.TextField()),
                ('read', models.BooleanField(default=False)),
                ('read_s', models.BooleanField(default=False)),
                ('chat_request', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.ChatRequest')),
                ('responder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
