# Generated by Django 3.0.8 on 2023-02-03 16:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20230111_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatrequest',
            name='message_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 3, 22, 13, 48, 609044)),
        ),
        migrations.AlterField(
            model_name='chatresponse',
            name='message_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 3, 22, 13, 48, 609898)),
        ),
        migrations.AlterField(
            model_name='companyannouncement',
            name='announcement_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 3, 22, 13, 48, 602093)),
        ),
        migrations.AlterField(
            model_name='companyannouncement',
            name='last_date_to_apply',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 3, 22, 13, 48, 602072)),
        ),
        migrations.AlterField(
            model_name='notification',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 3, 22, 13, 48, 607452)),
        ),
        migrations.AlterField(
            model_name='session',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 3, 22, 13, 48, 600434)),
        ),
        migrations.AlterField(
            model_name='studentregistration',
            name='date_of_registrations',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 3, 22, 13, 48, 603302)),
        ),
    ]
