# Generated by Django 3.0.8 on 2023-01-11 18:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatrequest',
            name='message_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 11, 23, 59, 43, 16466)),
        ),
        migrations.AlterField(
            model_name='chatresponse',
            name='message_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 11, 23, 59, 43, 16612)),
        ),
        migrations.AlterField(
            model_name='companyannouncement',
            name='announcement_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 11, 23, 59, 43, 15496)),
        ),
        migrations.AlterField(
            model_name='companyannouncement',
            name='last_date_to_apply',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 11, 23, 59, 43, 15490)),
        ),
        migrations.AlterField(
            model_name='notification',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 11, 23, 59, 43, 16347)),
        ),
        migrations.AlterField(
            model_name='session',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 11, 23, 59, 43, 15013)),
        ),
        migrations.AlterField(
            model_name='studentregistration',
            name='date_of_registrations',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 11, 23, 59, 43, 15798)),
        ),
    ]
